import 'package:flutter/material.dart';
import '../models/product_model.dart';

class HomeVM extends ChangeNotifier {
  final List<Product> products = [
    // ===== Laptops =====
    Product(
      id: '1',
      name: 'MSI Laptop',
      image: 'assets/hp.png',
      price: 30000,
      rating: 4.5,
      description: 'High performance gaming laptop',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '2',
      name: 'Mac',
      image: 'assets/Mac.png',
      price: 25000,
      rating: 4.0,
      description: 'Reliable laptop for work and study',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '3',
      name: 'Acer Predator',
      image: 'assets/acer.png',
      price: 27000,
      rating: 4.2,
      description: 'Gaming laptop with powerful GPU',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '4',
      name: 'Samsung Notebook',
      image: 'assets/samsung.png',
      price: 26000,
      rating: 4.0,
      description: 'Lightweight laptop for everyday tasks',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '5',
      name: 'HP Pavilion',
      image: 'assets/hpp.png',
      price: 25500,
      rating: 4.1,
      description: 'Affordable laptop with solid performance',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '6',
      name: 'Dell XPS',
      image: 'assets/dv.png',
      price: 32000,
      rating: 4.6,
      description: 'Premium laptop for professionals',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),
    Product(
      id: '7',
      name: 'Lenovo ThinkPad',
      image: 'assets/lenovo.png',
      price: 28000,
      rating: 4.3,
      description: 'Business laptop with excellent keyboard',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Laptop',
    ),

    // ===== Mobiles =====
    Product(
      id: '8',
      name: 'Samsung Galaxy S25',
      image: 'assets/Galaxy-S25-Edge.png',
      price: 18000,
      rating: 4.4,
      description: 'Latest Samsung flagship phone',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'mobile',
    ),
    Product(
      id: '9',
      name: 'iPhone 11',
      image: 'assets/iPhone 11 Pro.png',
      price: 20000,
      rating: 4.5,
      description: 'Popular Apple smartphone',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'mobile',
    ),
    Product(
      id: '10',
      name: 'Samsung Galaxy',
      image: 'assets/Samsung Galaxy.png',
      price: 17000,
      rating: 4.3,
      description: 'Samsung mid-range smartphone',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'mobile',
    ),
    Product(
      id: '11',
      name: 'Samsung Galaxy S24',
      image: 'assets/Samsung-Galaxy-S24.png',
      price: 19000,
      rating: 4.4,
      description: 'Flagship Samsung phone with excellent camera',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'mobile',
    ),
    Product(
      id: '12',
      name: 'Samsung Galaxy S25',
      image: 'assets/Samsung-Galaxy-S25.png',
      price: 21000,
      rating: 4.5,
      description: 'New generation Samsung smartphone',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'mobile',
    ),

    // ===== Accessories =====
    Product(
      id: '13',
      name: 'Portable Charger',
      image: 'assets/Pngtree.png',
      price: 800,
      rating: 4.2,
      description: 'High capacity portable charger',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Accessories',
    ),
    Product(
      id: '14',
      name: 'Wireless Mouse',
      image: 'assets/wireless_mouse.jpg',
      price: 600,
      rating: 4.0,
      description: 'Ergonomic wireless mouse',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Accessories',
    ),
    Product(
      id: '15',
      name: 'Smart Watch',
      image: 'assets/smart_watch.jpg',
      price: 2500,
      rating: 4.3,
      description: 'Track your fitness and notifications',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Accessories',
    ),
    Product(
      id: '16',
      name: 'Headphones',
      image: 'assets/head_phone.jpg',
      price: 1200,
      rating: 4.1,
      description: 'High quality over-ear headphones',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Accessories',
    ),
    Product(
      id: '17',
      name: 'AirPods',
      image: 'assets/airpods.png',
      price: 3500,
      rating: 4.4,
      description: 'Wireless Apple AirPods',
      colors: [0xFF6D6D6D, 0xFF000000],
      category: 'Accessories',
    ),
  ];

  List<Product> getSimilarProducts(Product product) {
    return products
        .where((p) => p.category == product.category && p.id != product.id)
        .toList();
  }
}
